series_id: KOBSIXMER
series_name: BoK, BSI, Export Sales Growth, Manufacturing, Forecast
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Export
nan_method: 2
standardization: true
units: Index
category: Survey, Bsnss
release: -35
