series_id: KOBSIBNER
series_name: BoK, BSI, Business Conditions, Non-Manufacturing, Forecast
frequency: m
transformation: chg
blocks:
- Block_Global
nan_method: 2
standardization: true
units: Index
category: Survey, Bsnss
release: -35
