series_id: KOBSIHAPR
series_name: BoK, BSI, Employment Conditions, All Industries, Actual
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Labor
nan_method: 2
standardization: true
units: Index
category: Survey, Bsnss
release: -5
