series_id: KOCALL.
series_name: Bank of Korea Base Rate
frequency: m
transformation: chg
blocks:
- Block_Global
nan_method: 2
standardization: true
units: Percent, Annual
category: Finance
release: 1
