series_id: KOCSEMEMR
series_name: CSI, Expectations of Employment Situation, Total
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Consumption
- Block_Labor
nan_method: 2
standardization: true
units: Index
category: Survey, Cnsmr
release: -5
