series_id: KOCSMTTOA
series_name: Cyber Shopping Mall, Transaction Amount, Total, Total, KRW
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Consumption
- Block_Nominal
nan_method: 2
standardization: true
units: Index
category: Consumption
release: 32
