series_id: KOEMPWREP
series_name: Employment, Wholesale and Retail Trade
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Consumption
- Block_Labor
nan_method: 2
standardization: true
units: Thousands of Persons
category: Labor
release: 11
