series_id: KOEMPMANF
series_name: Employment, Mining and Manufacturing
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Labor
nan_method: 2
standardization: true
units: Thousands of Persons
category: Labor
release: 11
