series_id: KOEQUIPTE
series_name: Investment, Equipment, Estimation, SA
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Investment
nan_method: 2
standardization: true
units: Index
category: Investment
release: 30
