series_id: KOEQUIMAE
series_name: Investment, Machinery, SA, Index
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Investment
nan_method: 2
standardization: true
units: Index
category: Investment
release: 30
