series_id: KOEXCHINA
series_name: Exports, China, USD
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Export
- Block_Nominal
nan_method: 2
standardization: true
units: $, Millions
category: Int. trade
release: 1
