series_id: KOGDP...D
series_name: GDP, Constant Prices
frequency: q
transformation: cha
# blocks: optional - if not specified, defaults to first block in model config
# blocks:
#   - Block_Global
nan_method: 2
standardization: true
units: Chained W, Billions
category: Macro
release: 25
