series_id: KOLRLTCO
series_name: Lending Rates, Loans to Corporations (On New Lending), Average
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Investment
nan_method: 2
standardization: true
units: Percent, Annual
category: Finance
release: 30
