series_id: KOMPCAPGG
series_name: Production, Capital Goods, SA
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Investment
nan_method: 2
standardization: true
units: Index
category: Production
release: 30
