series_id: KOUN%TOTQ
series_name: Unemployed, Rate, Total, SA
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Labor
nan_method: 2
standardization: true
units: Percent
category: Labor
release: 11
