series_id: KOVALCONA
series_name: Construction Completed, Total, KRW
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Investment
- Block_Nominal
nan_method: 2
standardization: true
units: Index
category: Investment
release: 30
