series_id: KOWRCNODE
series_name: Wholesale and Retail Trade, Total, Non-Durable Goods, SA
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Consumption
nan_method: 2
standardization: true
units: Index
category: Consumption
release: 28
