series_id: KOWRCCNSE
series_name: Retail Sales, Total, SA
frequency: m
transformation: chg
blocks:
- Block_Global
- Block_Consumption
nan_method: 2
standardization: true
units: Index
category: Consumption
release: 28
